Repository antoniosaints/organiza-soft, pull requests merged in 2024-08, with the labels that each got.

#4 FEAT: added new style method to microcomponents and type to backend
  api/prisma/schema.prisma
  vue/components.json
  vue/package.json
  vue/src/assets/index.css
  vue/src/components/styles/buttons/btnStyle.ts
  vue/src/components/styles/tags/tagStyle.ts
  vue/src/components/ui/button/Button.vue
  vue/src/components/ui/button/index.ts
  vue/src/components/ui/dropdown-menu/DropdownMenu.vue
  vue/src/components/ui/dropdown-menu/DropdownMenuCheckboxItem.vue
  vue/src/components/ui/dropdown-menu/DropdownMenuContent.vue
  vue/src/components/ui/dropdown-menu/DropdownMenuGroup.vue
  vue/src/components/ui/dropdown-menu/DropdownMenuItem.vue
  vue/src/components/ui/dropdown-menu/DropdownMenuLabel.vue
  vue/src/components/ui/dropdown-menu/DropdownMenuRadioGroup.vue
  vue/src/components/ui/dropdown-menu/DropdownMenuRadioItem.vue
  vue/src/components/ui/dropdown-menu/DropdownMenuSeparator.vue
  vue/src/components/ui/dropdown-menu/DropdownMenuShortcut.vue
  vue/src/components/ui/dropdown-menu/DropdownMenuSub.vue
  vue/src/components/ui/dropdown-menu/DropdownMenuSubContent.vue
  vue/src/components/ui/dropdown-menu/DropdownMenuSubTrigger.vue
  vue/src/components/ui/dropdown-menu/DropdownMenuTrigger.vue
  vue/src/components/ui/dropdown-menu/index.ts
  vue/src/components/ui/input/Input.vue
  vue/src/components/ui/input/index.ts
  vue/src/components/ui/label/Label.vue
  vue/src/components/ui/label/index.ts
  vue/src/components/ui/switch/Switch.vue
  vue/src/components/ui/switch/index.ts
  vue/src/lib/utils.ts
  vue/src/main.ts
  vue/src/types/transacao/IParcelamento.ts
  vue/src/types/transacao/ITransacao.ts
  vue/src/types/usuarios/IUsuario.ts
  vue/src/views/LoginView.vue
  vue/src/views/Usuarios/MobileCardsUsuarios.vue
  vue/src/views/Usuarios/UsuariosView.vue
  vue/tailwind.config.js
  vue/vite.config.ts
Labels: help wanted

#10 [feat]Adicionando tipagem a request e response/Corrigindo erro de tip…
  api/src/controllers/assinatura_controller.ts
  api/src/controllers/auth_controller.ts
  api/src/controllers/categorias_controller.ts
  api/src/controllers/cliente_controller.ts
  api/src/controllers/contas_controller.ts
  api/src/controllers/grupos_controller.ts
  api/src/controllers/parcelamento_controller.ts
  api/src/controllers/permissoes_controller.ts
  api/src/controllers/transacao_controller.ts
  api/src/controllers/usuario_controller.ts
  api/src/middlewares/auth_middleware.ts
  api/src/services/response_service.ts
  api/src/services/upload_service.ts
Labels: enhancement

#11 Fix service upload
  api/src/controllers/transacao_controller.ts
  api/src/services/upload_service.ts
Labels: bug
